Resolves #11 and #10

diff --git a/keycrypt b/keycrypt
--- a/keycrypt
+++ b/keycrypt
@@ -239,6 +239,12 @@ function askCopyPubKey() {
 	esac
 }
 
+function checkApplicationInstalled() {
+	local APP=$1
+	
+	command -v $APP >/dev/null 2>&1 || { echo >&2 "I require $APP but it's not installed.  Aborting."; exit 1; }
+}
+
 function generatePassword() {
 	TMP_PASS=$(openssl rand -base64 128)
 }
@@ -267,14 +273,16 @@ EOF
 ##################################      Entry Point     ##################################
 ##########################################################################################
 
+checkApplicationInstalled "openssl"
 generatePassword
+
 
 case $1 in
 	"hello" )
 		echo "Hello, $2"
 		;;
 	[tT][eE][sS][tT] ) #test
-		echo "$TMP_PASS"
+		checkApplicationInstalled "foo"
 		;;
 	[cC][rR][eE][aA][tT][eE] | [cC][rR] ) #create
 		defaultKeyLocation $2
