Resolves #2 added in check for copying key

diff --git a/keygen b/keygen
--- a/keygen
+++ b/keygen
@@ -151,8 +151,8 @@ function checkKeyExistence() {
 	fi
 }
 
-function exportKey() {
-	local KEY=$GKEY
+function copyPubKey() {
+	local KEY=$1
 	local PUBKEY="$GKEY.pub"
 	local ID=""
 	local SERVER=""
@@ -182,9 +182,27 @@ function exportKey() {
 		echo "The key supplied doesn't exist."
 	fi
 
-	# COMMAND="$COMMAND "
-
 	{ eval "$ID" ; } | ssh $PARAMS "umask 077; test -d .ssh || mkdir .ssh ; cat >> .ssh/authorized_keys; test -x /sbin/restorecon && /sbin/restorecon .ssh .ssh/authorized_keys" || exit 1
+}
+
+function askCopyPubKey() {
+	local KEY=$1
+
+	echo -n "Would you like to copy this key (y/n)? "
+	read INPUT
+
+	case $INPUT in
+		[yY][eE][sS] | [yY] )
+			copyPubKey $KEY
+			;;
+		[nN][oO] | [nN] )
+			exit 1
+			;;
+		* )
+			echo "Invalid Option"
+			exit 1
+			;;
+	esac
 }
 
 function usage() {
@@ -192,10 +210,13 @@ function usage() {
 Usage
 ------
 
-create 		This will create a new key and then encrypt it.
-			You should supply a keyname and/or path.
-encrypt 	This will encrypt a pre-existing key.
-			Supply the path to the key.
+create (cr) 		This will create a new key and then encrypt it.
+					You should supply a keyname and/or path.
+
+encrypt (enc)		This will encrypt a pre-existing key.
+					Supply the path to the key.
+
+copy (cp)			Copies the inputted ID to a prompted server.
 
 ---------------------------------------------------------
 
@@ -215,16 +236,20 @@ case $1 in
 	[tT][eE][sS][tT] )
 		defaultKeyLocation $2
 		echo "$GKEY"
-		exportKey $GKEY
 		;;
-	[cC][rR][eE][aA][tT][eE] )
+	[cC][rR][eE][aA][tT][eE] | [cC][rR] )
 		defaultKeyLocation $2
 		checkKeyExistence $GKEY
 		encryptKey $GKEY
+		askCopyPubKey $GKEY
 		;;
 	[eE][nN][cC][rR][yY][pP][tT] | [eE][nN][cC])
 		defaultKeyLocation $2
 		encryptKey $2
+		;;
+	[cC][oO][pP][yY] | [cC][pP] )
+		defaultKeyLocation $2
+		copyPubKey $GKEY
 		;;
 	[vV][eE][rR][sS][iI][oO][nN] | [vV] | [vV][eE][rR] )
 		echo "keygen v$VERSION"
